config/routes.rb
BookApp::Application.routes.draw do
  root to: "books#index"

  get 'books/about'
  get 'authors/about'
  resources :books

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :title, presence: { message: I18n.t("messages.validate.title") }
  validates :author, presence: { message: I18n.t("messages.validate.author") }
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  layout "author"

  def about
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :get_page
  before_action :get_book, only: [:edit, :update, :destroy]
  before_action :get_books, only: [:index, :edit]

  def index
    @book = Book.new(released_date: Time.now)
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Book was successfully added.'
    else
      render action: 'index'
    end
  end

  def edit
    render action: 'index'
  end

  def update
    if @book.update(book_params)
       redirect_to books_path, notice: 'Book was successfully updated.'
    else
       render action: 'index'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: "#{@book.title} was successfully deleted."
  end

  def about
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def get_page
      @@page ||= 1
      @@page = params[:page].to_i if params[:page]
    end
    def get_book
      @book = Book.find(params[:id])
    end
    def get_books
      @books = Book.paginate(page: @@page, per_page: 10)
      if @@page > 1 && @books.empty?
        @@page -= 1
        @books = Book.paginate(page: @@page, per_page: 10)
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :released_date, :author_id,
        :rating, :available)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/about.html.erb
<div class="header-container">
  <header class="wrapper clearfix">
    <h1 class="title"><%= "#{controller_name}##{action_name}" %></h1>
    <nav class="leaf-menu">
      <ul>
        <li><%= link_to "Book", books_path %>
          <div id="book"></div></li>
        <li><%= link_to "Author", authors_about_path %>
          <div id="author"></div></li>
        <li><%= link_to "About", books_about_path %>
          <div id="about"></div></li>
      </ul>
    </nav>
  </header>
</div>
<div class="main-container">
  <div class="main wrapper clearfix">
    <article>
      <header>
        <h2>Lorem Ipsum คืออะไร</h2>
        <p>Posted on <time datetime="2009-09-04T16:31:24+02:00">September 4th 2009</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
      </header>
      <p>Lorem Ipsum คือ เนื้อหาจำลองแบบเรียบๆ ที่ใช้กันในธุรกิจงานพิมพ์หรืองานเรียงพิมพ์ มันได้กลายมาเป็นเนื้อหาจำลองมาตรฐานของธุรกิจดังกล่าวมาตั้งแต่ศตวรรษที่ 16 เมื่อเครื่องพิมพ์โนเนมเครื่องหนึ่งนำรางตัวพิมพ์มาสลับสับตำแหน่งตัวอักษรเพื่อทำหนังสือตัวอย่าง Lorem Ipsum อยู่ยงคงกระพันมาไม่ใช่แค่เพียงห้าศตวรรษ แต่อยู่มาจนถึงยุคที่พลิกโฉมเข้าสู่งานเรียงพิมพ์ด้วยวิธีทางอิเล็กทรอนิกส์ และยังคงสภาพเดิมไว้อย่างไม่มีการเปลี่ยนแปลง มันได้รับความนิยมมากขึ้นในยุค ค.ศ. 1960 เมื่อแผ่น Letraset วางจำหน่ายโดยมีข้อความบนนั้นเป็น Lorem Ipsum และล่าสุดกว่านั้น คือเมื่อซอฟท์แวร์การทำสื่อสิ่งพิมพ์ (Desktop Publishing) อย่าง Aldus PageMaker ได้รวมเอา Lorem Ipsum เวอร์ชั่นต่างๆ เข้าไว้ในซอฟท์แวร์ด้วย</p>
    </article>
    <aside>
      <h2>ทำไมจึงต้องนำมาใช้</h2>
      <p>มีหลักฐานที่เป็นข้อเท็จจริงยืนยันมานานแล้ว ว่าเนื้อหาที่อ่านรู้เรื่องนั้นจะไปกวนสมาธิของคนอ่านให้เขวไปจากส่วนที้เป็น Layout เรานำ Lorem Ipsum มาใช้เพราะความที่มันมีการกระจายของตัวอักษรธรรมดาๆ แบบพอประมาณ ซึ่งเอามาใช้แทนการเขียนว่า ‘ตรงนี้เป็นเนื้อหา, ตรงนี้เป็นเนื้อหา' ได้ และยังทำให้มองดูเหมือนกับภาษาอังกฤษที่อ่านได้ปกติ ปัจจุบันมีแพ็กเกจของซอฟท์แวร์การทำสื่อสิ่งพิมพ์ และซอฟท์แวร์การสร้างเว็บเพจ (Web Page Editor) หลายตัวที่ใช้ Lorem Ipsum เป็นแบบจำลองเนื้อหาที่เป็นค่าตั้งต้น และเวลาที่เสิร์ชด้วยคำว่า 'lorem ipsum' ผลการเสิร์ชที่ได้ก็จะไม่พบบรรดาเว็บไซต์ที่ยังคงอยู่ในช่วงเริ่มสร้างด้วย โดยหลายปีที่ผ่านมาก็มีการคิดค้นเวอร์ชั่นต่างๆ ของ Lorem Ipsum ขึ้นมาใช้ บ้างก็เป็นความบังเอิญ บ้างก็เป็นความตั้งใจ (เช่น การแอบแทรกมุกตลก)</p>
    </aside>

    <article>
      <header>
        <h2>มันมีที่มาอย่างไร</h2>
        <p>Posted on <time datetime="2009-09-04T16:31:24+02:00">September 4th 2009</time> by <a href="#">Writer</a> - <a href="#comments">6 comments</a></p>
      </header>
      <p>ตรงกันข้ามกับความเชื่อที่นิยมกัน Lorem Ipsum ไม่ได้เป็นเพียงแค่ชุดตัวอักษรที่สุ่มขึ้นมามั่วๆ แต่หากมีที่มาจากวรรณกรรมละตินคลาสสิกชิ้นหนึ่งในยุค 45 ปีก่อนคริสตศักราช ทำให้มันมีอายุถึงกว่า 2000 ปีเลยทีเดียว ริชาร์ด แมคคลินท็อค ศาสตราจารย์ชาวละติน จากวิทยาลัยแฮมพ์เด็น-ซิดนีย์ ในรัฐเวอร์จิเนียร์ นำคำภาษาละตินคำว่า consectetur ซึ่งหาคำแปลไม่ได้จาก Lorem Ipsum ตอนหนึ่งมาค้นเพิ่มเติม โดยตรวจเทียบกับแหล่งอ้างอิงต่างๆ ในวรรณกรรมคลาสสิก และค้นพบแหล่งข้อมูลที่ไร้ข้อกังขาว่า Lorem Ipsum นั้นมาจากตอนที่ 1.10.32 และ 1.10.33 ของเรื่อง "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) ของ ซิเซโร ที่แต่งไว้เมื่อ 45 ปีก่อนคริสตศักราช หนังสือเล่มนี้เป็นเรื่องราวที่ว่าด้วยทฤษฎีแห่งจริยศาสตร์ ซึ่งเป็นที่นิยมมากในยุคเรเนสซองส์ บรรทัดแรกของ Lorem Ipsum "Lorem ipsum dolor sit amet.." ก็มาจากบรรทัดหนึ่งในตอนที่ 1.10.32 นั่นเอง</p>
    </article>
  </div>
</div>
<div class="footer-container">
  <footer class="wrapper">
    <h3>Copyright &copy;2013</h3>
  </footer>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.js"></script>
<script>window.jQuery || document.write('<script src="/assets/jquery-1.10.1.js"><\/script>')</script> <script>window.jQuery || document.write('<script src="/assets/jquery-1.10.1.js"><\/script>')</script>

app/views/books/_footer.html.erb
<div class="footer-container">
  <footer class="wrapper">
    <h3>&copy;418342</h3>
  </footer>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <div class="<%= action_name %>">
    <table>
      <tr>
        <th><%= t "labels.title" %></th>
        <td><%= f.text_field :title, size: 30 %></td>
        <th><%= t "labels.author" %></th>
        <td><%= f.collection_select :author_id, Author.all,
          :id, :name, { prompt: true, length: 25 },
          { style: "width: 150px;" } %></td></tr>
      <tr>
        <th><%= t "labels.released" %></th>
        <td><%= f.date_field :released_date %></td>
        <th><%= t "labels.rating" %></th>
        <td><%= f.range_field :rating, in: 0..5, step: 1,
          id: "book#{@book.id}" %>
          <div class="rateit" data-rateit-backingfld="#book<%= @book.id %>"></div></td>
        <th><%= t "labels.available" %></th>
        <td><%= f.check_box :available %></td></tr>
    </table>
  </div>
  <%= f.submit options = {class: "button_#{action_name}"} %>
<% end %>

app/views/books/_headmenu.html.erb
<div class="header-container">
  <header class="wrapper clearfix">
    <h1 class="title">Book Entry</h1>
    <nav <%= "class=leaf-menu" if (Time.now.to_i/60)%2 == 0 %>>
      <ul>
        <li><%= link_to "Book", books_path, 'data-no-turbolink' => true %><div id="orange"></div></li>
        <li><%= link_to "Author", authors_about_path %><div id="blue"></div></li>
        <li><%= link_to "About", books_about_path %><div id="purple"></div></li>
      </ul>
    </nav>
  </header>
</div>

app/views/books/_message.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

app/views/books/about.html.erb
<h1>About</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/books/index.html.erb
<%= render 'message' %>

<% if @books && !@books.empty? %>
  <table class="display">
    <tr>
      <th class="wider"><%= t "labels.title" %></th>
      <th class="wide"><%= t "labels.author" %></th>
      <th class="tight"><%= t "labels.released" %></th>
      <th class="tight"><%= t "labels.rating" %></th>
      <th class="tighter"><%= t "labels.available" %></th>
      <th class="tighter"><%= t "labels.actions" %></th>
    </tr>
    <% for book in @books do %>
      <tr>
        <td class="wider"><%= book.title %></td>
        <td class="wide"><%= book.author.name if book.author %></td>
        <td class="tight"><%= l book.released_date if book.released_date %></td>
        <td class="tight">
          <div class="rateit" data-rateit-value="<%= book.rating %>" data-rateit-ispreset="true" data-rateit-readonly="true"></div></td>
        <td <%= "class=avail" if book.available %>></td>
        <td><%= link_to image_tag("/assets/icons/action_save.gif"), edit_book_path(book) %>
        <%= link_to image_tag("/assets/icons/action_stop.gif"), book, class: 'delete', method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
    <% end %>
  </table>
  <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @books %>
    </div>
    <%= will_paginate @books, container: false %>
  </div>
  <br>
<% end %>

<%= render 'form' %>

<%= coffee_script_tag do %>
  $(document).on 'page:change', ->
    $('.rateit').rateit()
    return
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Application</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'books/headmenu' %>
    <div class="main wrapper clearfix">
      <%= yield %>
    </div>
    <%= render 'books/footer' %>
  </body>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Application</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>